<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DirectorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $directivos = [
            [
                'titulo'           => 'M.C.',
                'nombre'           => 'José Rubén',
                'apellido_paterno' => 'Solórzano',
                'apellido_materno' => 'Carbajal',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'rector',
                'identificador'    => 'rector',
                'zona_escolar'     => null,
                'sector'          => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
            [
                'titulo'           => 'M.S.P.',
                'nombre'           => 'Silvia',
                'apellido_paterno' => 'Agustín',
                'apellido_materno' => 'Magaña',
                'curp'             => 'AUMS730210MGRGGL04',
                'rfc'              => 'AUMS730210SZ7',
                'cargo'            => 'Directora General',
                'identificador'    => 'directora-general',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => '7671045146',
                'correo'           => null,
                'genero'           => 'F',
                'status'           => true,
            ],
            [
                'titulo'           => 'M.C.',
                'nombre'           => 'Angélica',
                'apellido_paterno' => 'Ocampo',
                'apellido_materno' => 'Agustín',
                'curp'             => 'OAAA910116MGRCGN07',
                'rfc'              => 'OAAA910116CF2',
                'cargo'            => 'Directora',
                'identificador'    => 'directora',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => '7671068113',
                'correo'           => 'ANGEL_AZUL_OA@HOTMAIL.COM',
                'genero'           => 'F',
                'status'           => true,
            ],
            [
                'titulo'           => 'Lic.',
                'nombre'           => 'Mariano',
                'apellido_paterno' => 'Marcelo',
                'apellido_materno' => 'Mendez',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'subdirector',
                'identificador'    => 'subdirector',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
            [
                'titulo'           => 'Profr.',
                'nombre'           => 'Nahún',
                'apellido_paterno' => 'Rivera',
                'apellido_materno' => 'Milián',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'Supervisor Escolar',
                'identificador'    => 'supervisor-secundaria',
                'zona_escolar'     => '02',
                'sector'           => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
            [
                'titulo'           => 'Profr.',
                'nombre'           => 'Adelfo',
                'apellido_paterno' => 'Martínez',
                'apellido_materno' => 'Martínez',
                'curp'             => 'MAMA540328HGRRRD08',
                'rfc'              => 'MAMA540328LK2',
                'cargo'            => 'Supervisor Escolar',
                'identificador'    => 'supervisor-primaria',
                'zona_escolar'     => '030',
                'sector'           => '01',
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
            [
                'titulo'           => 'Dra.',
                'nombre'           => 'Yamileth',
                'apellido_paterno' => 'García',
                'apellido_materno' => 'Durán',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'Supervisora Escolar',
                'identificador'    => 'supervisor-preescolar',
                'zona_escolar'     => '137',
                'sector'           => '03',
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'F',
                'status'           => true,
            ],
            [
                'titulo'           => 'Profr.',
                'nombre'           => 'Taurino',
                'apellido_paterno' => 'Vázquez',
                'apellido_materno' => 'Vázquez',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'Delegado de Servicios Educativos Región: Tierra Caliente',
                'identificador'    => 'delegado-servicios-educativos-tierra-caliente',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
            [
                'titulo'           => 'Ing.',
                'nombre'           => 'Oscar Francisco',
                'apellido_paterno' => 'Herrera',
                'apellido_materno' => 'Vázquez',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'Director General de Administracion y Desarrollo de Personal del Gobierno del Edo. Chilpancingo, Gro',
                'identificador'    => 'director-general-administracion',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'M',
                'status'           => true,
            ],
             [
                'titulo'           => 'M.C.',
                'nombre'           => 'Leticia',
                'apellido_paterno' => 'Nava',
                'apellido_materno' => 'López',
                'curp'             => null,
                'rfc'              => null,
                'cargo'            => 'Directora de Magisterio Estatal Gobierno del Estado de Guerrero',
                'identificador'    => 'director-magisterio-estatal',
                'zona_escolar'     => null,
                'sector'           => null,
                'telefono'         => null,
                'correo'           => null,
                'genero'           => 'F',
                'status'           => true,

            ]
        ];

        foreach ($directivos as $directivo) {
            \App\Models\Director::create($directivo);
        }
    }
}
