<div class="space-y-5">
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
        <flux:select wire:model.live="generacion_id" label="Generación"><flux:select.option value="">Todas</flux:select.option>@foreach($generaciones as $g)<flux:select.option value="{{ $g->id }}">{{ $g->etiqueta }}{{ $g->status ? '' : ' · inactiva' }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model.live="grado_id" label="Grado"><flux:select.option value="">Todos</flux:select.option>@foreach($grados as $g)<flux:select.option value="{{ $g->id }}">{{ $g->nombre }}</flux:select.option>@endforeach</flux:select>
        @if($slug_nivel==='bachillerato')<flux:select wire:model.live="semestre_id" label="Semestre"><flux:select.option value="">Todos</flux:select.option>@foreach($semestres as $s)<flux:select.option value="{{ $s->id }}">{{ $s->numero }}</flux:select.option>@endforeach</flux:select>@endif
        <flux:select wire:model.live="grupo_id" label="Grupo"><flux:select.option value="">Todos</flux:select.option>@foreach($grupos as $g)<flux:select.option value="{{ $g->id }}">{{ $g->asignacionGrupo?->nombre ?? $g->id }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model.live="estado" label="Estatus"><flux:select.option value="todos">Todos</flux:select.option>@foreach($this->categorias as $valor=>$texto)<flux:select.option value="{{ $valor }}">{{ $texto }}</flux:select.option>@endforeach</flux:select>
        <label class="flex items-center gap-2 rounded-xl border px-3 py-2 text-sm dark:border-neutral-700"><input type="checkbox" wire:model.live="solo_ya_no_estan"> Solo no activos</label>
    </div>
    <div class="flex flex-wrap justify-end gap-2"><flux:button wire:click="limpiarFiltros" variant="ghost">Limpiar</flux:button><a target="_blank" href="{{ $this->urlPdf }}" class="rounded-xl border px-4 py-2 text-sm font-bold">PDF</a><a href="{{ $this->urlExcel }}" class="rounded-xl border px-4 py-2 text-sm font-bold">Excel</a><a href="{{ $this->urlZip }}" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">ZIP</a></div>

    @forelse($this->bloques as $bloque)
        <section class="overflow-hidden rounded-2xl border dark:border-neutral-800"><div class="flex items-center justify-between bg-slate-900 px-4 py-3 text-white"><b>{{ $bloque['ciclo'] }}</b><span class="text-xs">Total {{ $bloque['totales']['total_historico'] }}</span></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr><th class="p-3 text-left">Grado</th>@if($slug_nivel==='bachillerato')<th class="p-3">Sem.</th>@endif<th class="p-3">Grupo</th><th class="p-3">H</th><th class="p-3">M</th><th class="p-3">Total</th><th class="p-3">Activos</th><th class="p-3">Bajas</th><th class="p-3">Traslados</th><th class="p-3">Egresados</th></tr></thead><tbody class="divide-y dark:divide-neutral-800">@foreach($bloque['filas'] as $fila)<tr><td class="p-3 font-bold">{{ $fila['grado'] }}</td>@if($slug_nivel==='bachillerato')<td class="p-3 text-center">{{ $fila['semestre'] }}</td>@endif<td class="p-3 text-center">{{ $fila['grupo'] }}</td><td class="p-3 text-center">{{ $fila['hombres'] }}</td><td class="p-3 text-center">{{ $fila['mujeres'] }}</td><td class="p-3 text-center font-black">{{ $fila['total_historico'] }}</td><td class="p-3 text-center">{{ $fila['activos'] }}</td><td class="p-3 text-center">{{ $fila['bajas'] }}</td><td class="p-3 text-center">{{ $fila['traslados'] }}</td><td class="p-3 text-center">{{ $fila['egresados'] }}</td></tr>@endforeach</tbody></table></div></section>
    @empty<div class="rounded-2xl border border-dashed p-10 text-center text-slate-500">Sin alumnos para los filtros seleccionados.</div>@endforelse

    <section class="overflow-hidden rounded-2xl border dark:border-neutral-800"><div class="border-b p-4 font-black dark:border-neutral-800">Listado nominal</div><div class="max-h-[520px] overflow-auto"><table class="min-w-full text-sm"><thead class="sticky top-0 bg-slate-50 dark:bg-neutral-950"><tr><th class="p-3 text-left">Alumno</th><th class="p-3">Generación</th><th class="p-3">Ubicación</th><th class="p-3">Estatus</th><th class="p-3">Fecha</th></tr></thead><tbody class="divide-y dark:divide-neutral-800">@foreach($this->listado as $fila)<tr><td class="p-3"><b>{{ $fila['alumno'] }}</b><div class="text-xs text-slate-500">{{ $fila['matricula'] }} · {{ $fila['curp'] }}</div></td><td class="p-3 text-center">{{ $fila['generacion'] }}</td><td class="p-3 text-center">{{ $fila['grado'] }}@if($slug_nivel==='bachillerato') · Sem. {{ $fila['semestre'] }}@endif · {{ $fila['grupo'] }}</td><td class="p-3 text-center">{{ $fila['estado_actual'] }}</td><td class="p-3 text-center">{{ $fila['fecha_baja'] !== '—' ? $fila['fecha_baja'] : $fila['fecha_alta'] }}</td></tr>@endforeach</tbody></table></div></section>
</div>
