<div class="space-y-5">
    <div class="rounded-2xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900 dark:border-sky-900/50 dark:bg-sky-950/20 dark:text-sky-100">
        La promoción cambia únicamente la ubicación actual del alumno. La generación se conserva. Los no promovidos permanecen en el mismo grado o semestre.
    </div>
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <flux:select wire:model.live="generacion_id" label="Generación"><flux:select.option value="">Selecciona</flux:select.option>@foreach($generaciones as $g)<flux:select.option value="{{ $g->id }}">{{ $g->etiqueta }}{{ $g->status ? '' : ' · inactiva' }}</flux:select.option>@endforeach</flux:select>
        <flux:select wire:model.live="grado_origen_id" label="Grado actual"><flux:select.option value="">Selecciona</flux:select.option>@foreach($grados as $grado)<flux:select.option value="{{ $grado->id }}">{{ $grado->nombre }}</flux:select.option>@endforeach</flux:select>
        @if($this->esBachillerato())<flux:select wire:model.live="semestre_origen_id" label="Semestre actual"><flux:select.option value="">Selecciona</flux:select.option>@foreach($semestresOrigen as $s)<flux:select.option value="{{ $s->id }}">Semestre {{ $s->numero }}</flux:select.option>@endforeach</flux:select>@endif
        <flux:select wire:model.live="grupo_origen_id" label="Grupo actual"><flux:select.option value="">Selecciona</flux:select.option>@foreach($gruposOrigen as $grupo)<flux:select.option value="{{ $grupo->id }}">{{ $grupo->asignacionGrupo?->nombre ?? $grupo->id }}</flux:select.option>@endforeach</flux:select>
    </div>
    <div class="grid gap-4 rounded-2xl border border-emerald-200 bg-emerald-50/60 p-4 md:grid-cols-2 xl:grid-cols-4 dark:border-emerald-900/50 dark:bg-emerald-950/10">
        <flux:select wire:model.live="grado_destino_id" label="Grado destino"><flux:select.option value="">Selecciona</flux:select.option>@foreach($grados as $grado)<flux:select.option value="{{ $grado->id }}">{{ $grado->nombre }}</flux:select.option>@endforeach</flux:select>
        @if($this->esBachillerato())<flux:select wire:model.live="semestre_destino_id" label="Semestre destino"><flux:select.option value="">Selecciona</flux:select.option>@foreach($semestresDestino as $s)<flux:select.option value="{{ $s->id }}">Semestre {{ $s->numero }}</flux:select.option>@endforeach</flux:select>@endif
        <flux:select wire:model="grupo_destino_id" label="Grupo destino"><flux:select.option value="">Selecciona</flux:select.option>@foreach($gruposDestino as $grupo)<flux:select.option value="{{ $grupo->id }}">{{ $grupo->asignacionGrupo?->nombre ?? $grupo->id }}</flux:select.option>@endforeach</flux:select>
        <flux:input wire:model="motivo" label="Motivo obligatorio" placeholder="Promoción de fin de periodo" />
    </div>
    @error('seleccionados')<p class="text-sm font-bold text-rose-600">{{ $message }}</p>@enderror
    <div class="overflow-x-auto rounded-2xl border dark:border-neutral-800"><table class="min-w-full text-sm"><thead class="bg-slate-50 dark:bg-neutral-950"><tr><th class="p-3"><input type="checkbox" wire:model.live="seleccionarPagina"></th><th class="p-3 text-left">Alumno</th><th class="p-3 text-left">Estatus</th><th class="p-3 text-left">Ubicación</th></tr></thead><tbody class="divide-y dark:divide-neutral-800">@forelse($alumnos as $a)<tr><td class="p-3"><input type="checkbox" wire:model.live="seleccionados" value="{{ $a->id }}"></td><td class="p-3"><b>{{ trim($a->apellido_paterno.' '.$a->apellido_materno.' '.$a->nombre) }}</b><div class="text-xs text-slate-500">{{ $a->matricula }}</div></td><td class="p-3">{{ ucfirst(str_replace('_',' ',$a->estatus ?: 'activo')) }}</td><td class="p-3">{{ $a->grado?->nombre }}@if($a->semestre) · Sem. {{ $a->semestre->numero }}@endif · {{ $a->grupo?->asignacionGrupo?->nombre ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="p-8 text-center text-slate-500">Selecciona la generación y ubicación de origen.</td></tr>@endforelse</tbody></table></div>
    <div>{{ $alumnos->links() }}</div>
    <div class="flex flex-wrap justify-end gap-3"><flux:button wire:click="marcarNoPromovidos" variant="ghost" spinner="marcarNoPromovidos">Marcar no promovidos</flux:button><flux:button wire:click="promoverSeleccionados" variant="primary" spinner="promoverSeleccionados">Promover seleccionados</flux:button></div>
</div>
