<?php

return [
    'roles' => [
        'administrador' => [
            'label' => 'Administrador general',
            'permissions' => ['*'],
        ],
        'control_escolar' => [
            'label' => 'Control escolar',
            'permissions' => [
                'administracion.acceder', 'integridad.consultar', 'integridad.gestionar', 'seguimiento.consultar', 'seguimiento.gestionar', 'analitica.consultar', 'analitica.exportar', 'analitica.gestionar', 'auditoria.consultar',
                'notificaciones.gestionar', 'respaldos.gestionar', 'papelera.gestionar',
                'flujos.gestionar', 'alumnos.*', 'personal.*', 'academico.*',
                'calificaciones.*', 'documentos.*', 'horarios.*', 'fichas.*', 'calendario.*',
            ],
        ],
        'direccion' => [
            'label' => 'Dirección',
            'permissions' => [
                'administracion.acceder', 'integridad.consultar', 'seguimiento.consultar', 'seguimiento.gestionar', 'analitica.consultar', 'analitica.exportar', 'auditoria.consultar',
                'notificaciones.gestionar', 'flujos.gestionar', 'alumnos.consultar',
                'personal.consultar', 'academico.consultar', 'calificaciones.consultar',
                'calificaciones.autorizar', 'documentos.consultar', 'documentos.autorizar',
                'horarios.consultar', 'fichas.consultar', 'calendario.consultar', 'calendario.gestionar',
            ],
        ],
        'profesor' => [
            'label' => 'Profesor',
            'permissions' => [
                'horarios.consultar',
                'calificaciones.consultar',
                'calificaciones.capturar',
                'fichas.consultar',
                'fichas.capturar',
                'calendario.consultar',
            ],
        ],
        'consulta' => [
            'label' => 'Solo consulta',
            'permissions' => [
                'alumnos.consultar', 'personal.consultar', 'academico.consultar',
                'calificaciones.consultar', 'documentos.consultar', 'horarios.consultar',
                'fichas.consultar', 'calendario.consultar',
            ],
        ],
    ],

    'permissions' => [
        'administracion.acceder' => 'Acceder al centro de control',
        'integridad.consultar' => 'Consultar integridad académica',
        'integridad.gestionar' => 'Gestionar casos y aplicar correcciones de integridad',
        'seguimiento.consultar' => 'Consultar riesgo y seguimiento académico',
        'seguimiento.gestionar' => 'Gestionar planes, acciones y reglas de riesgo',
        'analitica.consultar' => 'Consultar analítica institucional avanzada',
        'analitica.exportar' => 'Exportar reportes ejecutivos de analítica',
        'analitica.gestionar' => 'Guardar instantáneas y administrar alertas directivas',
        'auditoria.consultar' => 'Consultar auditoría',
        'notificaciones.gestionar' => 'Gestionar notificaciones internas',
        'respaldos.gestionar' => 'Crear y consultar respaldos',
        'papelera.gestionar' => 'Restaurar elementos eliminados',
        'usuarios.gestionar' => 'Administrar usuarios y permisos',
        'configuracion.gestionar' => 'Modificar configuración central',
        'flujos.gestionar' => 'Administrar revisiones y cierres',
        'alumnos.consultar' => 'Consultar alumnos',
        'alumnos.crear' => 'Registrar alumnos',
        'alumnos.editar' => 'Editar alumnos',
        'alumnos.responsables_sensibles' => 'Gestionar tutela, autorizaciones de recogida y acceso académico de responsables',
        'alumnos.eliminar' => 'Eliminar alumnos',
        'personal.consultar' => 'Consultar personal',
        'personal.crear' => 'Registrar personal',
        'personal.editar' => 'Editar personal',
        'personal.eliminar' => 'Eliminar personal',
        'academico.consultar' => 'Consultar estructura académica',
        'academico.crear' => 'Crear estructura académica',
        'academico.editar' => 'Editar estructura académica',
        'academico.eliminar' => 'Eliminar estructura académica',
        'calificaciones.consultar' => 'Consultar calificaciones',
        'calificaciones.capturar' => 'Capturar calificaciones',
        'calificaciones.autorizar' => 'Autorizar calificaciones',
        'documentos.consultar' => 'Consultar documentos',
        'documentos.crear' => 'Crear documentos',
        'documentos.autorizar' => 'Autorizar documentos',
        'documentos.organizar' => 'Organizar páginas y administrar expedientes digitales',
        'documentos.eliminar' => 'Eliminar documentos',
        'horarios.consultar' => 'Consultar horarios',
        'horarios.editar' => 'Editar horarios',
        'horarios.publicar' => 'Publicar y programar versiones de horarios',
        'fichas.consultar' => 'Consultar fichas descriptivas',
        'fichas.capturar' => 'Capturar fichas descriptivas',
        'calendario.consultar' => 'Consultar el calendario operativo institucional',
        'calendario.gestionar' => 'Crear, editar, completar y archivar eventos institucionales',
    ],

    'policy_modules' => [
        'Accion' => 'academico',
        'AsignacionMateria' => 'academico',
        'CalendarioEvento' => 'calendario',
        'CicloEscolar' => 'academico',
        'Ciclo' => 'academico',
        'Director' => 'personal',
        'Escuela' => 'academico',
        'Generacion' => 'academico',
        'Grado' => 'academico',
        'Grupo' => 'academico',
        'Inscripcion' => 'alumnos',
        'InscripcionTutor' => 'alumnos',
        'Materia' => 'academico',
        'Nivel' => 'academico',
        'Periodo' => 'academico',
        'PersonaNivel' => 'personal',
        'Persona' => 'personal',
        'Semestre' => 'academico',
        'Tutor' => 'alumnos',
    ],
];
