<?php

return [
    'roles' => [
        'administrador' => [
            'label' => 'Administrador general',
            'permissions' => ['*'],
        ],
        'control_escolar' => [
            'label' => 'Control escolar',
            'permissions' => [
                'administracion.acceder', 'integridad.consultar', 'auditoria.consultar',
                'notificaciones.gestionar', 'respaldos.gestionar', 'papelera.gestionar',
                'flujos.gestionar', 'alumnos.*', 'personal.*', 'academico.*',
                'calificaciones.*', 'documentos.*', 'horarios.*',
            ],
        ],
        'direccion' => [
            'label' => 'Dirección',
            'permissions' => [
                'administracion.acceder', 'integridad.consultar', 'auditoria.consultar',
                'notificaciones.gestionar', 'flujos.gestionar', 'alumnos.consultar',
                'personal.consultar', 'academico.consultar', 'calificaciones.consultar',
                'calificaciones.autorizar', 'documentos.consultar', 'documentos.autorizar',
                'horarios.consultar',
            ],
        ],
        'profesor' => [
            'label' => 'Profesor',
            'permissions' => [
                'alumnos.consultar', 'academico.consultar', 'calificaciones.consultar',
                'calificaciones.capturar', 'documentos.consultar', 'horarios.consultar',
            ],
        ],
        'consulta' => [
            'label' => 'Solo consulta',
            'permissions' => [
                'alumnos.consultar', 'personal.consultar', 'academico.consultar',
                'calificaciones.consultar', 'documentos.consultar', 'horarios.consultar',
            ],
        ],
    ],

    'permissions' => [
        'administracion.acceder' => 'Acceder al centro de control',
        'integridad.consultar' => 'Consultar integridad académica',
        'auditoria.consultar' => 'Consultar auditoría',
        'notificaciones.gestionar' => 'Gestionar notificaciones internas',
        'respaldos.gestionar' => 'Crear y consultar respaldos',
        'papelera.gestionar' => 'Restaurar elementos eliminados',
        'usuarios.gestionar' => 'Administrar usuarios y permisos',
        'configuracion.gestionar' => 'Modificar configuración central',
        'flujos.gestionar' => 'Administrar revisiones y cierres',
        'alumnos.consultar' => 'Consultar alumnos',
        'alumnos.crear' => 'Registrar alumnos',
        'alumnos.editar' => 'Editar alumnos',
        'alumnos.eliminar' => 'Eliminar alumnos',
        'personal.consultar' => 'Consultar personal',
        'personal.crear' => 'Registrar personal',
        'personal.editar' => 'Editar personal',
        'personal.eliminar' => 'Eliminar personal',
        'academico.consultar' => 'Consultar estructura académica',
        'academico.crear' => 'Crear estructura académica',
        'academico.editar' => 'Editar estructura académica',
        'academico.eliminar' => 'Eliminar estructura académica',
        'calificaciones.consultar' => 'Consultar calificaciones',
        'calificaciones.capturar' => 'Capturar calificaciones',
        'calificaciones.autorizar' => 'Autorizar calificaciones',
        'documentos.consultar' => 'Consultar documentos',
        'documentos.crear' => 'Crear documentos',
        'documentos.autorizar' => 'Autorizar documentos',
        'documentos.eliminar' => 'Eliminar documentos',
        'horarios.consultar' => 'Consultar horarios',
        'horarios.editar' => 'Editar horarios',
    ],

    'policy_modules' => [
        'Accion' => 'academico',
        'AsignacionMateria' => 'academico',
        'CicloEscolar' => 'academico',
        'Ciclo' => 'academico',
        'Director' => 'personal',
        'Escuela' => 'academico',
        'GeneracionBasica' => 'academico',
        'Generacion' => 'academico',
        'Grado' => 'academico',
        'Grupo' => 'academico',
        'Inscripcion' => 'alumnos',
        'Materia' => 'academico',
        'Nivel' => 'academico',
        'Periodo' => 'academico',
        'PeriodosBachillerato' => 'academico',
        'PeriodosBasico' => 'academico',
        'PersonaNivel' => 'personal',
        'Persona' => 'personal',
        'Profesor' => 'personal',
        'Semestre' => 'academico',
        'Tutor' => 'alumnos',
    ],
];
